"""init

Revision ID: 73c8a899e20b
Revises: 
Create Date: 2026-06-26 11:47:33.973053
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '73c8a899e20b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_configs',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('api_key', sa.String(length=256), nullable=False),
    sa.Column('base_url', sa.String(length=256), server_default='', nullable=False),
    sa.Column('model_name', sa.String(length=64), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('remark', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_index(op.f('ix_api_key_configs_id'), 'api_key_configs', ['id'], unique=False)
    op.create_table('contract_types',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_contract_types_code'), 'contract_types', ['code'], unique=True)
    op.create_index(op.f('ix_contract_types_id'), 'contract_types', ['id'], unique=False)
    op.create_table('law_articles',
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=64), server_default='', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_law_source_category', 'law_articles', ['source', 'category'], unique=False)
    op.create_index(op.f('ix_law_articles_category'), 'law_articles', ['category'], unique=False)
    op.create_index(op.f('ix_law_articles_id'), 'law_articles', ['id'], unique=False)
    op.create_index(op.f('ix_law_articles_title'), 'law_articles', ['title'], unique=False)
    op.create_table('users',
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('nickname', sa.String(length=32), server_default='', nullable=False),
    sa.Column('avatar', sa.String(length=256), server_default='', nullable=False),
    sa.Column('gender', sa.Integer(), server_default='0', nullable=False),
    sa.Column('company_name', sa.String(length=64), server_default='', nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('role', sa.String(length=16), server_default='user', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), server_default='', nullable=False),
    sa.Column('ip_address', sa.String(length=45), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action_time', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('idx_audit_user_time', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('contract_templates',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('structure', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=16), server_default='V1.0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['contract_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_id', 'version', name='uq_template_type_version')
    )
    op.create_index(op.f('ix_contract_templates_id'), 'contract_templates', ['id'], unique=False)
    op.create_index(op.f('ix_contract_templates_name'), 'contract_templates', ['name'], unique=False)
    op.create_table('contracts',
    sa.Column('title', sa.String(length=128), server_default='', nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['contract_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contracts_owner_status', 'contracts', ['owner_id', 'status'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_table('contract_versions',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('change_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('uploader', sa.String(length=16), server_default='ours', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'version_number', name='uq_contract_version')
    )
    op.create_index('idx_version_contract_id', 'contract_versions', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_versions_id'), 'contract_versions', ['id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('clause_location', sa.String(length=128), nullable=False),
    sa.Column('risk_type', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), server_default='', nullable=False),
    sa.Column('legal_basis', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_contract_level', 'risk_assessments', ['contract_id', 'risk_level'], unique=False)
    op.create_index(op.f('ix_risk_assessments_id'), 'risk_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_risk_level'), 'risk_assessments', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_assessments_risk_type'), 'risk_assessments', ['risk_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_risk_type'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_level'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_id'), table_name='risk_assessments')
    op.drop_index('idx_risk_contract_level', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_contract_versions_id'), table_name='contract_versions')
    op.drop_index('idx_version_contract_id', table_name='contract_versions')
    op.drop_table('contract_versions')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index('idx_contracts_owner_status', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_contract_templates_name'), table_name='contract_templates')
    op.drop_index(op.f('ix_contract_templates_id'), table_name='contract_templates')
    op.drop_table('contract_templates')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_time', table_name='audit_logs')
    op.drop_index('idx_audit_action_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_law_articles_title'), table_name='law_articles')
    op.drop_index(op.f('ix_law_articles_id'), table_name='law_articles')
    op.drop_index(op.f('ix_law_articles_category'), table_name='law_articles')
    op.drop_index('idx_law_source_category', table_name='law_articles')
    op.drop_table('law_articles')
    op.drop_index(op.f('ix_contract_types_id'), table_name='contract_types')
    op.drop_index(op.f('ix_contract_types_code'), table_name='contract_types')
    op.drop_table('contract_types')
    op.drop_index(op.f('ix_api_key_configs_id'), table_name='api_key_configs')
    op.drop_table('api_key_configs')
    # ### end Alembic commands ###
